### ISSUE TITLE
Iasl crash

### ISSUE THREAD

**Issue by mirh** [acpica/acpica#173]
So.. Tl;dr

Just try to decompile the dsdt table I sent [here](https://github.com/acpica/acpica/issues/122#issuecomment-244115583), using the facp file I uploaded [here](https://github.com/acpica/acpica/files/460438/facp.txt) for external symbols. 

Yes, I know I wouldn't be expected to use *that* with `-e` switch, but I was hoping resolving the last two UnkknownObj (wherever they are defined) could help shedding light on the mystery about dev dull volition.

**Comment by zetalog** [comment]
Could you also upload the dsdt to the github as your facp?

Thanks

**Comment by mirh** [comment]
[DSDT.txt](https://github.com/acpica/acpica/files/461127/DSDT.txt)

**Comment by acpibob** [comment]
certainly not defined in the FADT (signature FACP). The only tables of interest are the DSDT and all SSDTs.
so, we need all of those.

**Comment by mirh** [comment]
And it would still be normal for an external argument to still be undefined even after providing all of the SSDTs?

**Comment by acpibob** [comment]
Are you talking about the UnknownObj  externals in the DSDT?

    External (_PR_.P001._PPC, IntObj)
    External (_PR_.P001._PSS, PkgObj)
    External (_PR_.P002, UnknownObj)
    External (_PR_.P002._PPC, UnknownObj)
    External (_PR_.TCNM, IntObj)
    External (_SB_.ALIB, MethodObj)    // 2 Arguments

In fact, P002 is not defined in the DSDT, SSDT1, nor SSDT2.
However, "UnknownObj" means that the disassembler has determined that the object is not a control method, but it doesn't really know what it is. These are not really serious, because the disassembled DSDT does actually compile.

There may be a dynamically loaded SSDT that contains P002.

**Comment by mirh** [comment]
Mhh.. `ls /sys/firmware/acpi/tables/dynamic` shows nothing.. Though indeed, I can see in dmesg there are these RSDP and XSDT tables that gets loaded. 

[Acpidump](6b1c755131d8a7a8572119b8b111fd5c9f326629) should be able to dump them, but even with -x and -r manual switch I still only get the usual 9 tables.

**Comment by acpibob** [comment]
It is possible that P002 simply does not exist in your tables. Even this can happen due to the modularity of the tables. Or it can be a bug in the DSDT.

**Comment by zetalog** [comment]
> Mhh..  ls /sys/firmware/acpi/tables/dynamic  shows nothing.. Though indeed, I can see in dmesg there are these RSDP and XSDT tables that gets loaded. 

The tables pointed to by RSDT/XSDT are static loaded tables, appearing under /sys/firmware/acpi/tables, nor /sys/firmware/acpi/tables/dynamic.

Thanks

**Comment by zetalog** [comment]
> And it would still be normal for an external argument to still be undefined even after providing all of the SSDTs?

I think this is normal, as interpreter of AML acts more like scripting language interpreter.
It cares no about such kind of integrity.

So if:
1. BIOS writers simply uses old ASL code and there is garbage not cleaned up;
2. acpidump cannot dump all tables from the system - especially there are dynamic tables having not been loaded by the system.

This then likely happens.
It's uncontrollable from the disassembler's point of view.

**Comment by mirh** [comment]
Nice to know. 
RSDT/XSDT aren't in /sys/firmware/acpi/tables though.

**Comment by acpibob** [comment]
It sounds like the discussion is finished, I'm closing this one.

**Comment by mirh** [comment]
Yes, but that was just accidental. 

The point (the crash) is still there.

**Comment by acpibob** [comment]
There were two issues, correct:
iasl -lm dsdt.dat
and this one:

                                                       11600:             }
Error    6126 -                             syntax error, unexpected '}' ^

both have been fixed.

**Comment by mirh** [comment]
`Iasl -e facp.dat -d dsdt.dat` crash is still there. 
I know you aren't expect to get any result *at all*, from such senseless command.. But a crash means a bug. 

(then I'm too of a rookie to know if missing RSDT, XSDT is something to be worried about or not)

**Comment by acpibob** [comment]
ok, sorry - I had forgotten what the original issue was.
I've reproduced it here, so we can get on it.
Do you get a bunch of output like this:

ACPI Error: Unknown opcode 0x18 at table offset 0x0039, ignoring (20160831/psobject-189)
/*
Error: Unknown opcode 0x18 at table offset 0x0039, context:
  0029: D0 2A 3D 00 02 09 00 B2 00 00 00 F0 F1 F2 00 00  // .*=.............
  0039: 18 00 00 00 00 00 00 04 18 00 00 00 00 00 00 50  // ...............P
  0049: 18 00 00 08 18 00 00 80 18 00 00 00 00 00 00 04  // ................
 */

**Comment by mirh** [comment]
Yes, albeit I hope you weren't using my files there, because I'm not getting any exact "0x18 at table offset 0x0039" here.

**Comment by acpibob** [comment]
I used local files to check how generic the problem is.
We ignore all non-AML files (non-DSDT/SSDT), but an FADT slips through.
The -e option simply ignores non-AML files, with an error message. Reported problem is fixed, not committed yet.

c:\0acpi-machines\skylake>iasl -e facp.dat -d dsdt.dat

Intel ACPI Component Architecture
ASL+ Optimizing Compiler version 20160831-32
Copyright (c) 2000 - 2016 Intel Corporation

Input file dsdt.dat, Length 0x2EAAE (191150) bytes
ACPI: DSDT 0x0000000000000000 02EAAE (v02 INTEL  SKL      00000000 INTL 20141107)
External object resolution file         facp.dat
Input file facp.dat, Length 0xF4 (244) bytes
    facp.dat: Table [FACP] is not an AML table - ignoring
Pass 1 parse of [DSDT]
Pass 2 parse of [DSDT]
Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)

Parsing completed

**Comment by mirh** [comment]
Fine then.

**Comment by acpibob** [comment]
Thanks for your help.
Please feel free to report any other issues you find.
bob

**Comment by mirh** [comment]
Well, there would be this missing tables mystery to possibly consider an issue.

**Comment by acpibob** [comment]
There may or may not be any missing tables. It may simply be a BIOS bug.
In any case, any issues here would probably be Linux-specific, not ACPICA.

I don't know if you have mentioned this, but is there actually a problem on the machine?

**Comment by mirh** [comment]
No, no absolutely. I was just looking for these possible dynamically loaded SSDT, when I noticed in dmesg RSDT and XSDT were mentioned "loaded". 
I couldn't find them anywhere though. 

No problems then (aside of a SystemIO error, that I hope your newest version has fixed).

**Comment by zetalog** [comment]
> RSDT/XSDT aren't in /sys/firmware/acpi/tables though.
ACPICA uses entries of RSDT/XSDT to generate the global table list, thus RSDT/XSDT themselves are not in the global table list.
So it is implementation specific, not a bug.
If you want to obtain RSDT/XSDT from the platforms, you can use "acpidump -c off".

Thanks
Lv

**Comment by mirh** [comment]
`Cannot map /dev/mem`
`Could not get ACPI tables, AE_ACCESS`

Dmesg notifies you then that acpidump tried to access /dev/mem. 
And after a quick search I found [this](https://lwn.net/Articles/267427/) and [this](https://patchwork.kernel.org/patch/7687101/) that could have something to do.

**Comment by zetalog** [comment]
Yes, you need sudo and need to enable /dev/mem support (CONFIG_DEVMEM).
Thus it is not the default option now.

**Comment by mirh** [comment]
Devmem is already enabled by default. 
The problem is STRICT_DEVMEM, which I had to [disable](https://github.com/torvalds/linux/blob/master/lib/Kconfig.debug#L1981) to have *indeed* rsdp, rsdt, xsdt. 

Alternatively, you could also just disable IO_STRICT_DEVMEM.

**Comment by zetalog** [comment]
I didn't try it.
I don't know why Linux cares so much about graded /dev/mem privileges.
IMO, simply only allowing root (not root privileged users) could be sufficient.
Next time we need to ask bug reporters to enable many configurable items in order to dump the real platform acpidump to confirm whether the reported bug is a created "theoretical/coverage bug".

Thanks

**Comment by mirh** [comment]
Mhh.. I found some reasoning [here](http://www.linuxjournal.com/magazine/anthony-lineberry-devmem-rootkits) and [there](http://lists.infradead.org/pipermail/linux-arm-kernel/2015-January/317338.html) about it. 

Still, aside of wondering why an attacker with root privileges should be even "considered", I don't understand why disallowing read in addition to write.

**Comment by mirh** [comment]
[:)](https://bugzilla.kernel.org/show_bug.cgi?id=172921)

Aside of that, now with latest iasl not-AML tables are skipped.. 
[RSDP](https://github.com/acpica/acpica/files/493189/rsdp.zip) though triggers a totally different warning (invalid table signature). 

I mean, it's not a problem in the end for me (no crashes), but I thought you could be interested.

**Comment by zetalog** [comment]
Decompiling RSDP is a problem now.
We have a bugzilla entry tracking utility table file loading function issues:
http://bugs.acpica.org/show_bug.cgi?id=1119
Fixing this (BZ 1119) should be able to bring RSDP decompilation back functioning.
