### ISSUE TITLE
Fresh iasl: round trip failure with optimization

### ISSUE THREAD

**Issue by nms42** [acpica/acpica#675]
Dsl file (in attachment) compiled with default switches results in incorrect aml file. No optimization (-oa) switch did not exhibit that. Log and dsl file are attached.

[round.log.zip](https://github.com/acpica/acpica/files/6154560/round.log.zip)
[dsdt-orig.dsl.zip](https://github.com/acpica/acpica/files/6154561/dsdt-orig.dsl.zip)

**Comment by SchmErik** [comment]
thanks for the report. I'm able to reproduce this. Is this a regression?

**Comment by SchmErik** [comment]
leaving  notes for myself - looks like the "-on" makes the issue go away. I'll look into this a little more

**Comment by SchmErik** [comment]
@nms42 if you compile with default switches, can the resulting AML boot an OS?

**Comment by nms42** [comment]
No, I did not tried to run AML code due to half baked state of my project.

**Comment by acpibob** [comment]
I've reproduced the problem here. I will chase down the problem next.
Bob

**Comment by acpibob** [comment]
Could you post the original binary (AML) file from the machine? An AcpiDump would suffice.
thanks,
bob

**Comment by nms42** [comment]
[DSDT.aml.zip](https://github.com/acpica/acpica/files/8541788/DSDT.aml.zip)
Original binary file was extracted, disassembled. Then .dsl file was edited (see dsdt-orig.dsl). At that point round trip problem happens.

**Comment by nms42** [comment]
I don't remember. May be just to disassemble dsdt.aml and compare result with dsdt-orig.dsl?

**Comment by acpibob** [comment]
I don't see the problem using a more recent version of iASL (version 20220331). You may want to try this.

**Comment by nms42** [comment]
Well, the problem (bug?) is still here. See attached log.

[round2.log.zip](https://github.com/acpica/acpica/files/8546300/round2.log.zip)

**Comment by acpibob** [comment]
These are the warnings that you see?

Parsing Deferred Opcodes (Methods/Buffers/Packages/Regions)
ACPI Warning: Invalid character(s) in name (0x5B0DA069), repaired: [****] (20220331/utstring-337)
ACPI Warning: Invalid character(s) in name (0x4E480054), repaired: [T*HN] (20220331/utstring-337)
ACPI Warning: Invalid character(s) in name (0xA168544F), repaired: [OT**] (20220331/utstring-337)
ACPI Warning: Invalid character(s) in name (0x00A4800A), repaired: [****] (20220331/utstring-337)

**Comment by nms42** [comment]
> These are the warnings that you see?

Yes, I do. That is a result of bug in compilation. that still ends with "success".

`cp dsdt-orig.dsl dsdt.dsl;
iasl -vi dsdt.dsl;
iasl -d dsdt.aml`

**Comment by nms42** [comment]
Oops! Sorry for early closing.

**Comment by acpibob** [comment]
I will need the SSDTs from the machine also. Perhaps just send the acpidump?

**Comment by acpibob** [comment]
Are you seeing this warning during disassembly?

 iASL Warning: There were 6 external control methods found during
 disassembly, but only 3 were resolved (3 unresolved). Additional
 ACPI tables may be required to properly disassemble the code. This
 resulting disassembler output file may not compile because the
 disassembler did not know how many arguments to assign to the
 unresolved methods. Note: SSDTs can be dynamically loaded at
 runtime and may or may not be available via the host OS.

 To specify the tables needed to resolve external control method
 references, the -e option can be used to specify the filenames.
 Example iASL invocations:
     iasl -e ssdt1.aml ssdt2.aml ssdt3.aml -d dsdt.aml
     iasl -e dsdt.aml ssdt2.aml -d ssdt1.aml
     iasl -e ssdt*.aml -d dsdt.aml

 In addition, the -fe option can be used to specify a file containing
 control method external declarations with the associated method
 argument counts. Each line of the file must be of the form:
     External (<method pathname>, MethodObj, <argument count>)
 Invocation:
     iasl -fe refs.txt -d dsdt.aml

**Comment by nms42** [comment]
Looks like you missed (overlooked?) the very first steps - compilation of dsdt-orig.dsl, where broken .asl was produced.
